package clinic.view;

import java.util.Date;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.SpinnerModel;
import clinic.controller.*;
import clinic.model.basic.*;

/**
 *
 * @author Prezes
 */
public class MainWindow extends javax.swing.JFrame {
    
    
    private MultiJpaController controller;

   
    /**
     * Creates new form MainWindow
     */
    public MainWindow(MultiJpaController mjc) {
        this.controller = mjc;
        initComponents();
    }
    
    public void setController(MultiJpaController mjc){
        this.controller = mjc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMainTabbedPane = new javax.swing.JTabbedPane();
        jDoctorsPanel = new javax.swing.JPanel();
        jDoctorsTabbedPane = new javax.swing.JTabbedPane();
        jDoctorSpecialtyPane = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jDoctorSpecialtyCombo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDoctorsList = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jDoctorSpecialtyEdit = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jDoctorPersonaliaEdit = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jDoctorEmploymentDateEdit = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPatientsByDoctorList = new javax.swing.JList<>();
        jSeparator1 = new javax.swing.JSeparator();
        jRemovePatientFromDoctorButton = new javax.swing.JButton();
        jDoctorSavePane = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jAddDoctorSpecialtyCombo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jDoctorAddLastNameEdit = new javax.swing.JTextField();
        jDoctorAddFirstNameEdit = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jAddProfessionalTitleCombo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jAddEmployedSinceDateSpinner = new javax.swing.JSpinner();
        jAddDoctorSaveButton = new javax.swing.JButton();
        jAddDoctorResetButton = new javax.swing.JButton();
        jDoctorEditPane = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jEditDoctorSpecialtyCombo = new javax.swing.JComboBox<>();
        jDoctorEditFirstNameEdit = new javax.swing.JTextField();
        jDoctorEditLastNameEdit = new javax.swing.JTextField();
        jEditProfessionalTitleCombo = new javax.swing.JComboBox<>();
        jEditEmployedSinceDateSpinner = new javax.swing.JSpinner();
        jEditDoctorSaveButton = new javax.swing.JButton();
        jEditDoctorResetButton = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jEditDoctorsList = new javax.swing.JList<>();
        jIllnessesPanel = new javax.swing.JPanel();
        jIllnessTabbedPane = new javax.swing.JTabbedPane();
        jIllnessSpecialtyName = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jIllnessSavePane = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jIllnessEditName = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPatientsPanel = new javax.swing.JPanel();
        jPatientsTabbedPane = new javax.swing.JTabbedPane();
        jPatientDoctorPane = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPatientIllnessPane = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPatientSavePane = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPatientEditPane = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jToolBar = new javax.swing.JToolBar();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuDoctorsList = new javax.swing.JMenuItem();
        jMenuDoctorsAdd = new javax.swing.JMenuItem();
        jMenuDoctorsEdit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuIllnessList = new javax.swing.JMenuItem();
        jMenuIllnessAdd = new javax.swing.JMenuItem();
        jMenuIllnessEdit = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuPatientsByDoctorList = new javax.swing.JMenuItem();
        jMenuPatientsByIllnessList = new javax.swing.JMenuItem();
        jMenuPatientAdd = new javax.swing.JMenuItem();
        jMenuPatientEdit = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Przychodnia Menedżer");
        setBackground(java.awt.Color.blue);
        setForeground(java.awt.Color.blue);

        jMainTabbedPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jDoctorsPanel.setBackground(new java.awt.Color(204, 204, 255));

        jDoctorsTabbedPane.setBackground(new java.awt.Color(204, 204, 255));
        jDoctorsTabbedPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jDoctorsTabbedPane.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jDoctorsTabbedPaneComponentShown(evt);
            }
        });

        jDoctorSpecialtyPane.setBackground(new java.awt.Color(204, 204, 255));
        jDoctorSpecialtyPane.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jDoctorSpecialtyPaneComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Wybierz specjalizację lekarską:");

        jDoctorSpecialtyCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jDoctorSpecialtyCombo.setSelectedIndex(-1);
        jDoctorSpecialtyCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jDoctorSpecialtyComboItemStateChanged(evt);
            }
        });
        jDoctorSpecialtyCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDoctorSpecialtyComboActionPerformed(evt);
            }
        });
        jDoctorSpecialtyCombo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDoctorSpecialtyComboPropertyChange(evt);
            }
        });

        jLabel2.setText("Wybierz lekarza z listy:");

        jDoctorsList.setModel(new DefaultListModel());
        jDoctorsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jDoctorsListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jDoctorsList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jDoctorSpecialtyCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDoctorSpecialtyCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Specjalizacja lekarza:");

        jDoctorSpecialtyEdit.setEditable(false);
        jDoctorSpecialtyEdit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("Personalia:");

        jDoctorPersonaliaEdit.setEditable(false);
        jDoctorPersonaliaEdit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jDoctorPersonaliaEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDoctorPersonaliaEditActionPerformed(evt);
            }
        });

        jLabel5.setText("Data zatrudnienia:");

        jDoctorEmploymentDateEdit.setEditable(false);
        jDoctorEmploymentDateEdit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jDoctorEmploymentDateEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDoctorEmploymentDateEditActionPerformed(evt);
            }
        });

        jLabel6.setText("Lista pacjentów przypisanych do lekarza:");

        jPatientsByDoctorList.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jPatientsByDoctorList);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jRemovePatientFromDoctorButton.setText("Wypisz pacjenta z listy");
        jRemovePatientFromDoctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRemovePatientFromDoctorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDoctorSpecialtyEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDoctorPersonaliaEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDoctorEmploymentDateEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(8, 8, 8)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jRemovePatientFromDoctorButton))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jDoctorSpecialtyEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jDoctorPersonaliaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jDoctorEmploymentDateEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRemovePatientFromDoctorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );

        javax.swing.GroupLayout jDoctorSpecialtyPaneLayout = new javax.swing.GroupLayout(jDoctorSpecialtyPane);
        jDoctorSpecialtyPane.setLayout(jDoctorSpecialtyPaneLayout);
        jDoctorSpecialtyPaneLayout.setHorizontalGroup(
            jDoctorSpecialtyPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDoctorSpecialtyPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDoctorSpecialtyPaneLayout.setVerticalGroup(
            jDoctorSpecialtyPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDoctorSpecialtyPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jDoctorSpecialtyPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jDoctorsTabbedPane.addTab("Lista wg specjalności", jDoctorSpecialtyPane);

        jDoctorSavePane.setBackground(new java.awt.Color(204, 204, 255));
        jDoctorSavePane.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jDoctorSavePaneComponentShown(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setText("Tytuł zawodowy: ");

        jAddDoctorSpecialtyCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jAddDoctorSpecialtyCombo.setSelectedIndex(-1);
        jAddDoctorSpecialtyCombo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jAddDoctorSpecialtyCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jAddDoctorSpecialtyComboItemStateChanged(evt);
            }
        });
        jAddDoctorSpecialtyCombo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jAddDoctorSpecialtyComboPropertyChange(evt);
            }
        });

        jLabel8.setText("Wybierz specjalizację lekarską:");

        jLabel9.setText("Imię:");

        jDoctorAddLastNameEdit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jDoctorAddFirstNameEdit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setText("Nazwisko:");

        jAddProfessionalTitleCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "lek. med.", "dr. n. med.", "dr hab. n. med.", "prof. n. med." }));

        jLabel11.setText("Data zatrudnienia:");

        jAddEmployedSinceDateSpinner.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1577895960000L), new java.util.Date(946743960000L), new java.util.Date(), java.util.Calendar.MONTH));
        jAddEmployedSinceDateSpinner.setEditor(new javax.swing.JSpinner.DateEditor(jAddEmployedSinceDateSpinner, "dd/MM/YYYY"));
        jAddEmployedSinceDateSpinner.setOpaque(false);

        jAddDoctorSaveButton.setText("Zapisz lekarza");
        jAddDoctorSaveButton.setActionCommand("");

        jAddDoctorResetButton.setText("Wyczyść dane");
        jAddDoctorResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddDoctorResetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDoctorAddFirstNameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jAddDoctorSpecialtyCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jAddEmployedSinceDateSpinner, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jAddProfessionalTitleCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jDoctorAddLastNameEdit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jAddDoctorSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jAddDoctorResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(449, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAddDoctorSpecialtyCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDoctorAddFirstNameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDoctorAddLastNameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAddProfessionalTitleCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jAddEmployedSinceDateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAddDoctorSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAddDoctorResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDoctorSavePaneLayout = new javax.swing.GroupLayout(jDoctorSavePane);
        jDoctorSavePane.setLayout(jDoctorSavePaneLayout);
        jDoctorSavePaneLayout.setHorizontalGroup(
            jDoctorSavePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDoctorSavePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDoctorSavePaneLayout.setVerticalGroup(
            jDoctorSavePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDoctorSavePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jDoctorsTabbedPane.addTab("Zapisz lekarza", jDoctorSavePane);

        jDoctorEditPane.setBackground(new java.awt.Color(204, 204, 255));
        jDoctorEditPane.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jDoctorEditPaneComponentShown(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel12.setText("Wybierz specjalizację lekarską:");

        jLabel13.setText("Imię:");

        jLabel14.setText("Nazwisko:");

        jLabel15.setText("Tytuł zawodowy: ");

        jLabel16.setText("Data zatrudnienia:");

        jEditDoctorSpecialtyCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jEditDoctorSpecialtyCombo.setSelectedIndex(-1);
        jEditDoctorSpecialtyCombo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jEditDoctorSpecialtyCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jEditDoctorSpecialtyComboItemStateChanged(evt);
            }
        });
        jEditDoctorSpecialtyCombo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jEditDoctorSpecialtyComboPropertyChange(evt);
            }
        });

        jDoctorEditFirstNameEdit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jDoctorEditLastNameEdit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jEditProfessionalTitleCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "lek. med", "dr. n. med", "dr hab. n. med", "prof. n. med" }));

        jEditEmployedSinceDateSpinner.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1577895960000L), new java.util.Date(946743960000L), new java.util.Date(), java.util.Calendar.MONTH));
        jEditEmployedSinceDateSpinner.setDoubleBuffered(true);
        jEditEmployedSinceDateSpinner.setEditor(new javax.swing.JSpinner.DateEditor(jEditEmployedSinceDateSpinner, "dd/MM/YYYY"));
        jEditEmployedSinceDateSpinner.setOpaque(false);

        jEditDoctorSaveButton.setText("Zapisz lekarza");
        jEditDoctorSaveButton.setActionCommand("");

        jEditDoctorResetButton.setText("Wyczyść dane");
        jEditDoctorResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditDoctorResetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDoctorEditFirstNameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEditDoctorSpecialtyCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jEditEmployedSinceDateSpinner, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                .addComponent(jEditProfessionalTitleCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jDoctorEditLastNameEdit, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jEditDoctorSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jEditDoctorResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEditDoctorSpecialtyCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDoctorEditFirstNameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDoctorEditLastNameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEditProfessionalTitleCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jEditEmployedSinceDateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEditDoctorSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEditDoctorResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(204, 204, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel17.setText("Wybierz lekarza z listy:");

        jEditDoctorsList.setModel(new DefaultListModel());
        jEditDoctorsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jEditDoctorsListValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jEditDoctorsList);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        javax.swing.GroupLayout jDoctorEditPaneLayout = new javax.swing.GroupLayout(jDoctorEditPane);
        jDoctorEditPane.setLayout(jDoctorEditPaneLayout);
        jDoctorEditPaneLayout.setHorizontalGroup(
            jDoctorEditPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDoctorEditPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDoctorEditPaneLayout.setVerticalGroup(
            jDoctorEditPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDoctorEditPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDoctorEditPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jDoctorsTabbedPane.addTab("Edytuj dane lekarza", jDoctorEditPane);

        javax.swing.GroupLayout jDoctorsPanelLayout = new javax.swing.GroupLayout(jDoctorsPanel);
        jDoctorsPanel.setLayout(jDoctorsPanelLayout);
        jDoctorsPanelLayout.setHorizontalGroup(
            jDoctorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDoctorsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDoctorsTabbedPane)
                .addGap(0, 0, 0))
        );
        jDoctorsPanelLayout.setVerticalGroup(
            jDoctorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDoctorsPanelLayout.createSequentialGroup()
                .addComponent(jDoctorsTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 415, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        jMainTabbedPane.addTab("Lekarze", jDoctorsPanel);

        jIllnessesPanel.setBackground(new java.awt.Color(102, 153, 255));

        jIllnessTabbedPane.setBackground(new java.awt.Color(102, 153, 255));
        jIllnessTabbedPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jIllnessSpecialtyName.setBackground(new java.awt.Color(102, 153, 255));

        jPanel5.setBackground(new java.awt.Color(102, 153, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 858, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jIllnessSpecialtyNameLayout = new javax.swing.GroupLayout(jIllnessSpecialtyName);
        jIllnessSpecialtyName.setLayout(jIllnessSpecialtyNameLayout);
        jIllnessSpecialtyNameLayout.setHorizontalGroup(
            jIllnessSpecialtyNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jIllnessSpecialtyNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jIllnessSpecialtyNameLayout.setVerticalGroup(
            jIllnessSpecialtyNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jIllnessSpecialtyNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jIllnessTabbedPane.addTab("Lista wg specjalności", jIllnessSpecialtyName);

        jIllnessSavePane.setBackground(new java.awt.Color(102, 153, 255));

        jPanel6.setBackground(new java.awt.Color(102, 153, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 858, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jIllnessSavePaneLayout = new javax.swing.GroupLayout(jIllnessSavePane);
        jIllnessSavePane.setLayout(jIllnessSavePaneLayout);
        jIllnessSavePaneLayout.setHorizontalGroup(
            jIllnessSavePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jIllnessSavePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jIllnessSavePaneLayout.setVerticalGroup(
            jIllnessSavePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jIllnessSavePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jIllnessTabbedPane.addTab("Zapisz nową chorobę", jIllnessSavePane);

        jIllnessEditName.setBackground(new java.awt.Color(102, 153, 255));

        jPanel7.setBackground(new java.awt.Color(102, 153, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 858, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jIllnessEditNameLayout = new javax.swing.GroupLayout(jIllnessEditName);
        jIllnessEditName.setLayout(jIllnessEditNameLayout);
        jIllnessEditNameLayout.setHorizontalGroup(
            jIllnessEditNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jIllnessEditNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jIllnessEditNameLayout.setVerticalGroup(
            jIllnessEditNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jIllnessEditNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jIllnessTabbedPane.addTab("Edytuj dane choroby", jIllnessEditName);

        javax.swing.GroupLayout jIllnessesPanelLayout = new javax.swing.GroupLayout(jIllnessesPanel);
        jIllnessesPanel.setLayout(jIllnessesPanelLayout);
        jIllnessesPanelLayout.setHorizontalGroup(
            jIllnessesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jIllnessesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jIllnessTabbedPane)
                .addContainerGap())
        );
        jIllnessesPanelLayout.setVerticalGroup(
            jIllnessesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jIllnessesPanelLayout.createSequentialGroup()
                .addComponent(jIllnessTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jMainTabbedPane.addTab("Choroby", jIllnessesPanel);

        jPatientsPanel.setBackground(new java.awt.Color(153, 204, 255));

        jPatientsTabbedPane.setBackground(new java.awt.Color(153, 204, 255));
        jPatientsTabbedPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPatientDoctorPane.setBackground(new java.awt.Color(153, 204, 255));

        jPanel8.setBackground(new java.awt.Color(153, 204, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 858, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPatientDoctorPaneLayout = new javax.swing.GroupLayout(jPatientDoctorPane);
        jPatientDoctorPane.setLayout(jPatientDoctorPaneLayout);
        jPatientDoctorPaneLayout.setHorizontalGroup(
            jPatientDoctorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPatientDoctorPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPatientDoctorPaneLayout.setVerticalGroup(
            jPatientDoctorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPatientDoctorPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jPatientsTabbedPane.addTab("Lista wg lekarza prowadzącego", jPatientDoctorPane);

        jPatientIllnessPane.setBackground(new java.awt.Color(153, 204, 255));

        jPanel9.setBackground(new java.awt.Color(153, 204, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 858, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPatientIllnessPaneLayout = new javax.swing.GroupLayout(jPatientIllnessPane);
        jPatientIllnessPane.setLayout(jPatientIllnessPaneLayout);
        jPatientIllnessPaneLayout.setHorizontalGroup(
            jPatientIllnessPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPatientIllnessPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPatientIllnessPaneLayout.setVerticalGroup(
            jPatientIllnessPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPatientIllnessPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jPatientsTabbedPane.addTab("Lista wg chorób", jPatientIllnessPane);

        jPatientSavePane.setBackground(new java.awt.Color(153, 204, 255));

        jPanel10.setBackground(new java.awt.Color(153, 204, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 858, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPatientSavePaneLayout = new javax.swing.GroupLayout(jPatientSavePane);
        jPatientSavePane.setLayout(jPatientSavePaneLayout);
        jPatientSavePaneLayout.setHorizontalGroup(
            jPatientSavePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPatientSavePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPatientSavePaneLayout.setVerticalGroup(
            jPatientSavePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPatientSavePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jPatientsTabbedPane.addTab("Dodaj pacjenta", jPatientSavePane);

        jPatientEditPane.setBackground(new java.awt.Color(153, 204, 255));

        jPanel11.setBackground(new java.awt.Color(153, 204, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 858, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPatientEditPaneLayout = new javax.swing.GroupLayout(jPatientEditPane);
        jPatientEditPane.setLayout(jPatientEditPaneLayout);
        jPatientEditPaneLayout.setHorizontalGroup(
            jPatientEditPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPatientEditPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPatientEditPaneLayout.setVerticalGroup(
            jPatientEditPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPatientEditPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jPatientsTabbedPane.addTab("Edytuj dane pacjenta", jPatientEditPane);

        javax.swing.GroupLayout jPatientsPanelLayout = new javax.swing.GroupLayout(jPatientsPanel);
        jPatientsPanel.setLayout(jPatientsPanelLayout);
        jPatientsPanelLayout.setHorizontalGroup(
            jPatientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPatientsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPatientsTabbedPane)
                .addContainerGap())
        );
        jPatientsPanelLayout.setVerticalGroup(
            jPatientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPatientsPanelLayout.createSequentialGroup()
                .addComponent(jPatientsTabbedPane)
                .addContainerGap())
        );

        jMainTabbedPane.addTab("Pacjenci", jPatientsPanel);

        jToolBar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar.setRollover(true);

        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        jMenu1.setText("Rejestr lekarzy");
        jMenu1.setToolTipText("");

        jMenuDoctorsList.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuDoctorsList.setText("Lista wg specjalności");
        jMenuDoctorsList.setActionCommand("");
        jMenuDoctorsList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDoctorsListActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuDoctorsList);

        jMenuDoctorsAdd.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        jMenuDoctorsAdd.setText("Zapisz lekarza");
        jMenuDoctorsAdd.setToolTipText("");
        jMenuDoctorsAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDoctorsAddActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuDoctorsAdd);

        jMenuDoctorsEdit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuDoctorsEdit.setText("Edytuj dane lekarza");
        jMenuDoctorsEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDoctorsEditActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuDoctorsEdit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Rejestr chorób");
        jMenu2.setToolTipText("");

        jMenuIllnessList.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuIllnessList.setLabel("Lista wg specjalności");
        jMenuIllnessList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIllnessListActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuIllnessList);

        jMenuIllnessAdd.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMenuIllnessAdd.setText("Zapisz nową chorobę");
        jMenuIllnessAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIllnessAddActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuIllnessAdd);

        jMenuIllnessEdit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuIllnessEdit.setText("Edytuj dane choroby");
        jMenuIllnessEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIllnessEditActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuIllnessEdit);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Rejestr pacjentów");

        jMenuPatientsByDoctorList.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuPatientsByDoctorList.setText("Lista wg lekarza prowadzącego");
        jMenuPatientsByDoctorList.setToolTipText("");
        jMenuPatientsByDoctorList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPatientsByDoctorListActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuPatientsByDoctorList);

        jMenuPatientsByIllnessList.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuPatientsByIllnessList.setText("Lista wg chorób");
        jMenuPatientsByIllnessList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPatientsByIllnessListActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuPatientsByIllnessList);

        jMenuPatientAdd.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jMenuPatientAdd.setText("Dodaj pacjenta");
        jMenuPatientAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPatientAddActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuPatientAdd);

        jMenuPatientEdit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuPatientEdit.setLabel("Edytuj dane pacjenta");
        jMenuPatientEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPatientEditActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuPatientEdit);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jMainTabbedPane))
                    .addComponent(jToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jMainTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jMainTabbedPane.getAccessibleContext().setAccessibleName("Lekarze");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuIllnessEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIllnessEditActionPerformed
        jMainTabbedPane.setSelectedIndex(1);
        jIllnessTabbedPane.setSelectedIndex(2);
    }//GEN-LAST:event_jMenuIllnessEditActionPerformed

    private void jMenuDoctorsListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDoctorsListActionPerformed
        jMainTabbedPane.setSelectedIndex(0);
        jDoctorsTabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_jMenuDoctorsListActionPerformed

    private void jMenuDoctorsAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDoctorsAddActionPerformed
        jMainTabbedPane.setSelectedIndex(0);
        jDoctorsTabbedPane.setSelectedIndex(1);
    }//GEN-LAST:event_jMenuDoctorsAddActionPerformed

    private void jMenuDoctorsEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDoctorsEditActionPerformed
        jMainTabbedPane.setSelectedIndex(0);
        jDoctorsTabbedPane.setSelectedIndex(2);
    }//GEN-LAST:event_jMenuDoctorsEditActionPerformed

    private void jMenuIllnessListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIllnessListActionPerformed
        jMainTabbedPane.setSelectedIndex(1);
        jIllnessTabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_jMenuIllnessListActionPerformed

    private void jMenuIllnessAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIllnessAddActionPerformed
        jMainTabbedPane.setSelectedIndex(1);
        jIllnessTabbedPane.setSelectedIndex(1);
    }//GEN-LAST:event_jMenuIllnessAddActionPerformed

    private void jMenuPatientsByDoctorListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPatientsByDoctorListActionPerformed
        jMainTabbedPane.setSelectedIndex(2);
        jPatientsTabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_jMenuPatientsByDoctorListActionPerformed

    private void jMenuPatientsByIllnessListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPatientsByIllnessListActionPerformed
        jMainTabbedPane.setSelectedIndex(2);
        jPatientsTabbedPane.setSelectedIndex(1);
    }//GEN-LAST:event_jMenuPatientsByIllnessListActionPerformed

    private void jMenuPatientAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPatientAddActionPerformed
        jMainTabbedPane.setSelectedIndex(2);
        jPatientsTabbedPane.setSelectedIndex(2);
    }//GEN-LAST:event_jMenuPatientAddActionPerformed

    private void jMenuPatientEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPatientEditActionPerformed
        jMainTabbedPane.setSelectedIndex(2);
        jPatientsTabbedPane.setSelectedIndex(3);
    }//GEN-LAST:event_jMenuPatientEditActionPerformed

    private void jDoctorPersonaliaEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDoctorPersonaliaEditActionPerformed

    }//GEN-LAST:event_jDoctorPersonaliaEditActionPerformed

    private void jDoctorEmploymentDateEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDoctorEmploymentDateEditActionPerformed

    }//GEN-LAST:event_jDoctorEmploymentDateEditActionPerformed

    private void jDoctorSpecialtyPaneComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jDoctorSpecialtyPaneComponentShown
        SpecialtyJpaController specialtyController = controller.getSpecialtyJpaController();
        jDoctorSpecialtyCombo.removeAllItems();
        
        int specialtyCount = specialtyController.getSpecialtyCount();
        if (specialtyCount == 0)
            return;
        
        List<Specialty> specialties = specialtyController.findSpecialtyEntities();
        for (Specialty s : specialties)
        {
            String specialtyName = s.getSpecialtyName();
            jDoctorSpecialtyCombo.addItem(specialtyName);
        }
    }//GEN-LAST:event_jDoctorSpecialtyPaneComponentShown

    private void jDoctorSpecialtyComboPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDoctorSpecialtyComboPropertyChange
      
    }//GEN-LAST:event_jDoctorSpecialtyComboPropertyChange

    private void jDoctorSpecialtyComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jDoctorSpecialtyComboItemStateChanged
    }//GEN-LAST:event_jDoctorSpecialtyComboItemStateChanged

    private void jDoctorSpecialtyComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDoctorSpecialtyComboActionPerformed
    
        String param = evt.paramString();
        
        //jDoctorPersonaliaEdit.setText(""+jDoctorSpecialtyCombo.getSelectedIndex());
        DefaultListModel listModel = (DefaultListModel)(jDoctorsList.getModel());
        listModel.removeAllElements();
        
        DoctorJpaController doctorController = controller.getDoctorJpaController();
        
        int doctorCount = doctorController.getDoctorCount();
        if (doctorCount == 0)
            return;
        
        String specialtyName = (String)jDoctorSpecialtyCombo.getSelectedItem();
        if (specialtyName == null)
            return;
        
        List<Doctor> doctors = doctorController.findDoctorEntitiesBySpecialty(specialtyName);
        
        int i = 0;
        for (Doctor d : doctors)
        {
            String doctorName = d.getFirstName() + " " + d.getLastName();
            listModel.add(i, doctorName);
            i++;
        }
        
        
    }//GEN-LAST:event_jDoctorSpecialtyComboActionPerformed

    private String dateToString(Date date)
    {
        return "" + date.getDate()+"/"+(date.getMonth()+1)+"/"+(date.getYear()+1900);    
    }
    
    private void jDoctorsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jDoctorsListValueChanged
        
        String doctorName = jDoctorsList.getSelectedValue();
        if (doctorName == null)
            return;
        if (doctorName.length() == 0)
            return;
        
        String[] names = doctorName.split(" ");
        
        DoctorJpaController doctorController = controller.getDoctorJpaController();
        
        if (doctorController.getDoctorCount() == 0)
            return;
        
        Doctor d = doctorController.findDoctoryByFirstAndLastName(names[0], names[1]);
        jDoctorSpecialtyEdit.setText(d.getSpecialtyId().getSpecialtyName());
        jDoctorPersonaliaEdit.setText(d.getProfessionalTitle() + " " + d.getFirstName() + " " + d.getLastName());
        jDoctorEmploymentDateEdit.setText(dateToString(d.getEmployedSinceDate()));
        
        DefaultListModel patientsModel = (DefaultListModel)jPatientsByDoctorList.getModel();
        
        PatientJpaController patientController = controller.getPatientJpaController();
        if (patientController.getPatientCount() == 0)
            return;
        
        patientsModel.clear();
        List<Patient> patients = patientController.findPatientEntitiesByDoctorId(d.getDoctorId());
        int i = 0;
        
        for (Patient p : patients)
        {
            String patientName = p.getFirstName() + " " + p.getLastName();
            patientsModel.add(i, patientName);
            i++;
        }
    }//GEN-LAST:event_jDoctorsListValueChanged

    private void jRemovePatientFromDoctorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRemovePatientFromDoctorButtonActionPerformed

        String patientName = jPatientsByDoctorList.getSelectedValue();
        if (patientName == null)
            return;
        if (patientName.length() == 0)
            return;
        
       String[] names = patientName.split(" ");
       
       PatientJpaController patientController = controller.getPatientJpaController();
       Patient p = patientController.findPatientByName(names[0], names[1]);
       if (p == null)
           return;
       try
       {
            patientController.destroy(p.getPatientId());
       }
       catch(Exception ioe){
           return;
       }
       
       int index = jPatientsByDoctorList.getSelectedIndex();
       DefaultListModel model = (DefaultListModel)jPatientsByDoctorList.getModel();
       model.removeElementAt(index);
       
       
    }//GEN-LAST:event_jRemovePatientFromDoctorButtonActionPerformed

    private void jAddDoctorSpecialtyComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jAddDoctorSpecialtyComboItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jAddDoctorSpecialtyComboItemStateChanged

    private void jAddDoctorSpecialtyComboPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jAddDoctorSpecialtyComboPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jAddDoctorSpecialtyComboPropertyChange

    private void jEditDoctorSpecialtyComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jEditDoctorSpecialtyComboItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jEditDoctorSpecialtyComboItemStateChanged

    private void jEditDoctorSpecialtyComboPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jEditDoctorSpecialtyComboPropertyChange

        
    }//GEN-LAST:event_jEditDoctorSpecialtyComboPropertyChange

    private void jDoctorSavePaneComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jDoctorSavePaneComponentShown
        
        SpecialtyJpaController specialtyController = controller.getSpecialtyJpaController();
        jAddDoctorSpecialtyCombo.removeAllItems();
        
        int specialtyCount = specialtyController.getSpecialtyCount();
        if (specialtyCount == 0)
            return;
        
        List<Specialty> specialties = specialtyController.findSpecialtyEntities();
        for (Specialty s : specialties)
        {
            String specialtyName = s.getSpecialtyName();
            jAddDoctorSpecialtyCombo.addItem(specialtyName);
        }
        
    }//GEN-LAST:event_jDoctorSavePaneComponentShown

    private void jDoctorEditPaneComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jDoctorEditPaneComponentShown
        
        SpecialtyJpaController specialtyController = controller.getSpecialtyJpaController();
        jEditDoctorSpecialtyCombo.removeAllItems();
        
        int specialtyCount = specialtyController.getSpecialtyCount();
        if (specialtyCount == 0)
            return;
        
        List<Specialty> specialties = specialtyController.findSpecialtyEntities();
        for (Specialty s : specialties)
        {
            String specialtyName = s.getSpecialtyName();
            jEditDoctorSpecialtyCombo.addItem(specialtyName);
        }
        
        DefaultListModel model = (DefaultListModel)jEditDoctorsList.getModel();
        model.clear();
        DoctorJpaController doctorController = controller.getDoctorJpaController();
        if (doctorController.getDoctorCount() == 0)
            return;
        
        List<Doctor> doctors = doctorController.findDoctorEntities();
        int i = 0;
        for (Doctor d : doctors)
        {
            String fullName = d.getFirstName() + " " + d.getLastName();
            model.add(i, fullName);
            i++;
        }
                        
    }//GEN-LAST:event_jDoctorEditPaneComponentShown

    private void jAddDoctorResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddDoctorResetButtonActionPerformed
        
        if (jAddDoctorSpecialtyCombo.getItemCount() > 0)
        {
            jAddDoctorSpecialtyCombo.setSelectedIndex(0);
        }
        
        jDoctorAddFirstNameEdit.setText("");
        jDoctorAddLastNameEdit.setText("");
        jAddProfessionalTitleCombo.setSelectedIndex(0);
       // SpinnerModel model = jAddEmployedSinceDateSpinner.getModel();
        
    }//GEN-LAST:event_jAddDoctorResetButtonActionPerformed
   
    
    
    private void jEditDoctorsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jEditDoctorsListValueChanged
              
        DefaultListModel model = (DefaultListModel)jEditDoctorsList.getModel();
        if (model.getSize() == 0)
            return;
        
        String fullName = jEditDoctorsList.getSelectedValue();
        if (fullName == null)
            return;
        if (fullName.length() == 0)
            return;
        
        String[] names = fullName.split(" ");
        DoctorJpaController doctorController = controller.getDoctorJpaController();
        Doctor doctor = doctorController.findDoctoryByFirstAndLastName(names[0], names[1]);
        
        jDoctorEditFirstNameEdit.setText(doctor.getFirstName());
        jDoctorEditLastNameEdit.setText(doctor.getLastName());
        String title = doctor.getProfessionalTitle();
        jEditProfessionalTitleCombo.setSelectedItem(title);
        jEditDoctorSpecialtyCombo.setSelectedItem(doctor.getSpecialtyId().getSpecialtyName());
        Date employmentDate = doctor.getEmployedSinceDate();
        //String time = getDateString(employmentDate);
        jEditEmployedSinceDateSpinner.setValue(employmentDate);
                
    }//GEN-LAST:event_jEditDoctorsListValueChanged

    private String getDateString(Date date)
    {
        String time = "";
        int day = date.getDate();
        if (day < 10)
            time += "0";
        time += day;
        
        int month = date.getMonth();
        time += "/";
        
        if (month < 10)
            time += "0";
        time += month;
        
        int year = date.getYear() + 1900;
        time += "/" + year;

        return time;
    }
    
    
    private void jEditDoctorResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditDoctorResetButtonActionPerformed
       
        if (jEditDoctorSpecialtyCombo.getItemCount() > 0)
        {
            jEditDoctorSpecialtyCombo.setSelectedIndex(0);
        }
        
        jDoctorEditFirstNameEdit.setText("");
        jDoctorEditLastNameEdit.setText("");
        jEditProfessionalTitleCombo.setSelectedIndex(0);
       // SpinnerModel model = jAddEmployedSinceDateSpinner.getModel();
        
    }//GEN-LAST:event_jEditDoctorResetButtonActionPerformed

    private void jDoctorsTabbedPaneComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jDoctorsTabbedPaneComponentShown
       
        
       
               
    }//GEN-LAST:event_jDoctorsTabbedPaneComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddDoctorResetButton;
    private javax.swing.JButton jAddDoctorSaveButton;
    private javax.swing.JComboBox<String> jAddDoctorSpecialtyCombo;
    private javax.swing.JSpinner jAddEmployedSinceDateSpinner;
    private javax.swing.JComboBox<String> jAddProfessionalTitleCombo;
    private javax.swing.JTextField jDoctorAddFirstNameEdit;
    private javax.swing.JTextField jDoctorAddLastNameEdit;
    private javax.swing.JTextField jDoctorEditFirstNameEdit;
    private javax.swing.JTextField jDoctorEditLastNameEdit;
    private javax.swing.JPanel jDoctorEditPane;
    private javax.swing.JTextField jDoctorEmploymentDateEdit;
    private javax.swing.JTextField jDoctorPersonaliaEdit;
    private javax.swing.JPanel jDoctorSavePane;
    private javax.swing.JComboBox<String> jDoctorSpecialtyCombo;
    private javax.swing.JTextField jDoctorSpecialtyEdit;
    private javax.swing.JPanel jDoctorSpecialtyPane;
    private javax.swing.JList<String> jDoctorsList;
    private javax.swing.JPanel jDoctorsPanel;
    private javax.swing.JTabbedPane jDoctorsTabbedPane;
    private javax.swing.JButton jEditDoctorResetButton;
    private javax.swing.JButton jEditDoctorSaveButton;
    private javax.swing.JComboBox<String> jEditDoctorSpecialtyCombo;
    private javax.swing.JList<String> jEditDoctorsList;
    private javax.swing.JSpinner jEditEmployedSinceDateSpinner;
    private javax.swing.JComboBox<String> jEditProfessionalTitleCombo;
    private javax.swing.JPanel jIllnessEditName;
    private javax.swing.JPanel jIllnessSavePane;
    private javax.swing.JPanel jIllnessSpecialtyName;
    private javax.swing.JTabbedPane jIllnessTabbedPane;
    private javax.swing.JPanel jIllnessesPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jMainTabbedPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuDoctorsAdd;
    private javax.swing.JMenuItem jMenuDoctorsEdit;
    private javax.swing.JMenuItem jMenuDoctorsList;
    private javax.swing.JMenuItem jMenuIllnessAdd;
    private javax.swing.JMenuItem jMenuIllnessEdit;
    private javax.swing.JMenuItem jMenuIllnessList;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuPatientAdd;
    private javax.swing.JMenuItem jMenuPatientEdit;
    private javax.swing.JMenuItem jMenuPatientsByDoctorList;
    private javax.swing.JMenuItem jMenuPatientsByIllnessList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPatientDoctorPane;
    private javax.swing.JPanel jPatientEditPane;
    private javax.swing.JPanel jPatientIllnessPane;
    private javax.swing.JPanel jPatientSavePane;
    private javax.swing.JList<String> jPatientsByDoctorList;
    private javax.swing.JPanel jPatientsPanel;
    private javax.swing.JTabbedPane jPatientsTabbedPane;
    private javax.swing.JButton jRemovePatientFromDoctorButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar jToolBar;
    // End of variables declaration//GEN-END:variables
}
